FRANS VITO JONATHAN SIMAMORA

202410101147

DATAMINING A

In [2]:
import pandas as pd

In [3]:
df = pd.read_csv("iris(1).csv")
df

     sepal.length  sepal.width  petal.length  petal.width    variety
0             5.1          3.5           1.4          0.2     Setosa
1             4.9          3.0           1.4          0.2     Setosa
2             4.7          3.2           1.3          0.2     Setosa
3             4.6          3.1           1.5          0.2     Setosa
4             5.0          3.6           1.4          0.2     Setosa
..            ...          ...           ...          ...        ...
145           6.7          3.0           5.2          2.3  Virginica
146           6.3          2.5           5.0          1.9  Virginica
147           6.5          3.0           5.2          2.0  Virginica
148           6.2          3.4           5.4          2.3  Virginica
149           5.9          3.0           5.1          1.8  Virginica

[150 rows x 5 columns]

In [4]:
attribute_list = ["sepal.length", "sepal.width", "petal.length", "petal.width"]

In [5]:
for a in attribute_list:
  min =  df[a].min()
  max = df[a].max()
  df[a] = (df[a] - min) / (max-min)

df

     sepal.length  sepal.width  petal.length  petal.width    variety
0        0.222222     0.625000      0.067797     0.041667     Setosa
1        0.166667     0.416667      0.067797     0.041667     Setosa
2        0.111111     0.500000      0.050847     0.041667     Setosa
3        0.083333     0.458333      0.084746     0.041667     Setosa
4        0.194444     0.666667      0.067797     0.041667     Setosa
..            ...          ...           ...          ...        ...
145      0.666667     0.416667      0.711864     0.916667  Virginica
146      0.555556     0.208333      0.677966     0.750000  Virginica
147      0.611111     0.416667      0.711864     0.791667  Virginica
148      0.527778     0.583333      0.745763     0.916667  Virginica
149      0.444444     0.416667      0.694915     0.708333  Virginica

[150 rows x 5 columns]

In [56]:
class_iris = df["variety"].unique()
centroid = {}
for kelas_iris in class_iris:
  data_baru = df[df["variety"] == kelas_iris]
  centroid[kelas_iris] = {}
  for a in attribute_list :
    centroid[kelas_iris][a] = data_baru[a].mean()
    # print(kelas_iris, a)

centroid

{'Setosa': {'sepal.length': 0.19611111111111115,
  'sepal.width': 0.595,
  'petal.length': 0.0783050847457627,
  'petal.width': 0.06083333333333333},
 'Versicolor': {'sepal.length': 0.45444444444444443,
  'sepal.width': 0.3208333333333333,
  'petal.length': 0.5525423728813559,
  'petal.width': 0.5108333333333334},
 'Virginica': {'sepal.length': 0.6355555555555555,
  'sepal.width': 0.40583333333333327,
  'petal.length': 0.7715254237288136,
  'petal.width': 0.8025}}

In [57]:
iris_test = pd.read_csv("iristesting.csv")
iris_test

    sepal.length  sepal.width  petal.length  petal.width     variety
0            5.0          3.5           1.3          0.3      Setosa
1            4.5          2.3           1.3          0.3      Setosa
2            4.4          3.2           1.3          0.2      Setosa
3            5.0          3.5           1.6          0.6      Setosa
4            5.1          3.8           1.9          0.4      Setosa
5            4.8          3.0           1.4          0.3      Setosa
6            5.1          3.8           1.6          0.2      Setosa
7            4.6          3.2           1.4          0.2      Setosa
8            5.3          3.7           1.5          0.2      Setosa
9            5.0          3.3           1.4          0.2      Setosa
10           5.5          2.6           4.4          1.2  Versicolor
11           6.1          3.0           4.6          1.4  Versicolor
12           5.8          2.6           4.0          1.2  Versicolor
13           5.0          2.3           3.3          1.0  Versicolor
14           5.6          2.7           4.2          1.3  Versicolor
15           5.7          3.0           4.2          1.2  Versicolor
16           5.7          2.9           4.2          1.3  Versicolor
17           6.2          2.9           4.3          1.3  Versicolor
18           5.1          2.5           3.0          1.1  Versicolor
19           5.7          2.8           4.1          1.3  Versicolor
20           6.7          3.1           5.6          2.4   Virginica
21           6.9          3.1           5.1          2.3   Virginica
22           5.8          2.7           5.1          1.9   Virginica
23           6.8          3.2           5.9          2.3   Virginica
24           6.7          3.3           5.7          2.5   Virginica
25           6.7          3.0           5.2          2.3   Virginica
26           6.3          2.5           5.0          1.9   Virginica
27           6.5          3.0           5.2          2.0   Virginica
28           6.2          3.4           5.4          2.3   Virginica
29           5.9          3.0           5.1          1.8   Virginica

In [58]:
for a in attribute_list:
  min =  iris_test[a].min()
  max = iris_test[a].max()
  iris_test[a] = (iris_test[a] - min) / (max-min)

iris_test

    sepal.length  sepal.width  petal.length  petal.width     variety
0           0.24     0.800000      0.000000     0.043478      Setosa
1           0.04     0.000000      0.000000     0.043478      Setosa
2           0.00     0.600000      0.000000     0.000000      Setosa
3           0.24     0.800000      0.065217     0.173913      Setosa
4           0.28     1.000000      0.130435     0.086957      Setosa
5           0.16     0.466667      0.021739     0.043478      Setosa
6           0.28     1.000000      0.065217     0.000000      Setosa
7           0.08     0.600000      0.021739     0.000000      Setosa
8           0.36     0.933333      0.043478     0.000000      Setosa
9           0.24     0.666667      0.021739     0.000000      Setosa
10          0.44     0.200000      0.673913     0.434783  Versicolor
11          0.68     0.466667      0.717391     0.521739  Versicolor
12          0.56     0.200000      0.586957     0.434783  Versicolor
13          0.24     0.000000      0.434783     0.347826  Versicolor
14          0.48     0.266667      0.630435     0.478261  Versicolor
15          0.52     0.466667      0.630435     0.434783  Versicolor
16          0.52     0.400000      0.630435     0.478261  Versicolor
17          0.72     0.400000      0.652174     0.478261  Versicolor
18          0.28     0.133333      0.369565     0.391304  Versicolor
19          0.52     0.333333      0.608696     0.478261  Versicolor
20          0.92     0.533333      0.934783     0.956522   Virginica
21          1.00     0.533333      0.826087     0.913043   Virginica
22          0.56     0.266667      0.826087     0.739130   Virginica
23          0.96     0.600000      1.000000     0.913043   Virginica
24          0.92     0.666667      0.956522     1.000000   Virginica
25          0.92     0.466667      0.847826     0.913043   Virginica
26          0.76     0.133333      0.804348     0.739130   Virginica
27          0.84     0.466667      0.847826     0.782609   Virginica
28          0.72     0.733333      0.891304     0.913043   Virginica
29          0.60     0.466667      0.826087     0.695652   Virginica

In [60]:
for kelas_iris in class_iris:
  jarak = 0
  for a in attribute_list:
    jarak += (iris_test[a] - centroid[kelas_iris][a])**2
  jarak = jarak**(1/2)
  iris_test[kelas_iris] = jarak

iris_test

,sepal.length,sepal.width,petal.length,petal.width,variety,Setosa,Versicolor,Virginica
0,0.24,0.800000,0.000000,0.043478,Setosa,0.224464,0.894042,1.217866
1,0.04,0.000000,0.000000,0.043478,Setosa,0.620346,0.893545,1.300289
2,0.00,0.600000,0.000000,0.000000,Setosa,0.219811,0.922338,1.296491
3,0.24,0.800000,0.065217,0.173913,Setosa,0.238557,0.791573,1.098100
4,0.28,1.000000,0.130435,0.086957,Setosa,0.417687,0.921707,1.184252
5,0.16,0.466667,0.021739,0.043478,Setosa,0.145857,0.779832,1.169678
6,0.28,1.000000,0.065217,0.000000,Setosa,0.418252,0.995055,1.273708
7,0.08,0.600000,0.021739,0.000000,Setosa,0.142854,0.872265,1.246005
8,0.36,0.933333,0.043478,0.000000,Setosa,0.382417,0.950880,1.236222
9,0.24,0.666667,0.021739,0.000000,Setosa,0.118164,0.841600,1.196112
10,0.44,0.200000,0.673913,0.434783,Versicolor,0.842671,0.187947,0.474714
11,0.68,0.466667,0.717391,0.521739,Versicolor,0.933533,0.315336,0.295691
12,0.56,0.200000,0.586957,0.434783,Versicolor,0.828857,0.180861,0.466216
13,0.24,0.000000,0.434783,0.347826,Versicolor,0.751926,0.435154,0.800805
14,0.48,0.266667,0.630435,0.478261,Versicolor,0.817000,0.103515,0.410612
15,0.52,0.466667,0.630435,0.434783,Versicolor,0.752369,0.193432,0.414941
16,0.52,0.400000,0.630435,0.478261,Versicolor,0.788684,0.133015,0.372055
17,0.72,0.400000,0.652174,0.478261,Versicolor,0.903358,0.296268,0.355726
18,0.28,0.133333,0.369565,0.391304,Versicolor,0.643597,0.336682,0.728924
19,0.52,0.333333,0.608696,0.478261,Versicolor,0.793053,0.093102,0.387626
20,0.92,0.533333,0.934783,0.956522,Virginica,1.436534,0.778874,0.384110
21,1.00,0.533333,0.826087,0.913043,Virginica,1.391215,0.761175,0.405306
22,0.56,0.266667,0.826087,0.739130,Virginica,1.122267,0.375529,0.179077
23,0.96,0.600000,1.000000,0.913043,Virginica,1.469468,0.833973,0.455396
24,0.92,0.666667,0.956522,1.000000,Virginica,1.477312,0.859550,0.471352
25,0.92,0.466667,0.847826,0.913043,Virginica,1.363418,0.697836,0.320392
26,0.76,0.133333,0.804348,0.739130,Virginica,1.232206,0.494010,0.307954
27,0.84,0.466667,0.847826,0.782609,Virginica,1.242652,0.575304,0.227411
28,0.72,0.733333,0.891304,0.913043,Virginica,1.296467,0.719172,0.375438
29,0.60,0.466667,0.826087,0.695652,Virginica,1.068536,0.389151,0.139134

In [1]:
hasil_df = iris_test[class_iris]
# hasil_df
# hasil_df.min()
series_hasil =hasil_df.idxmin(axis=1)
series_hasil

NameError: name 'iris_test' is not defined

In [68]:
benar = (iris_test['variety'] == series_hasil).sum()

benar

29

In [69]:
total = len(iris_test)
akurasi = (benar/total)*100
print("akurasinya = ", akurasi, "%")

akurasinya =  96.66666666666667 %